//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MVCTesteModel", "FK_Cidade_Estado", "Estado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClienteMVC.Entity.Estado), "Cidade", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClienteMVC.Entity.Cidade), true)]
[assembly: EdmRelationshipAttribute("MVCTesteModel", "FK_Endereco_Cidade", "Cidade", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClienteMVC.Entity.Cidade), "Endereco", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClienteMVC.Entity.Endereco), true)]
[assembly: EdmRelationshipAttribute("MVCTesteModel", "FK_Endereco_Cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClienteMVC.Entity.Cliente), "Endereco", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClienteMVC.Entity.Endereco), true)]
[assembly: EdmRelationshipAttribute("MVCTesteModel", "FK_Modelo_Marca", "Marca", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClienteMVC.Entity.Marca), "Modelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClienteMVC.Entity.Modelo), true)]
[assembly: EdmRelationshipAttribute("MVCTesteModel", "FK_Produto_Modelo", "Modelo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClienteMVC.Entity.Modelo), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClienteMVC.Entity.Produto), true)]
[assembly: EdmRelationshipAttribute("MVCTesteModel", "FK_PerfilUsuario_Perfil", "Perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClienteMVC.Entity.Perfil), "PerfilUsuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClienteMVC.Entity.PerfilUsuario), true)]
[assembly: EdmRelationshipAttribute("MVCTesteModel", "FK_PerfilUsuario_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClienteMVC.Entity.Usuario), "PerfilUsuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClienteMVC.Entity.PerfilUsuario), true)]

#endregion

namespace ClienteMVC.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MVCTesteEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MVCTesteEntities object using the connection string found in the 'MVCTesteEntities' section of the application configuration file.
        /// </summary>
        public MVCTesteEntities() : base("name=MVCTesteEntities", "MVCTesteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MVCTesteEntities object.
        /// </summary>
        public MVCTesteEntities(string connectionString) : base(connectionString, "MVCTesteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MVCTesteEntities object.
        /// </summary>
        public MVCTesteEntities(EntityConnection connection) : base(connection, "MVCTesteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cidade> Cidade
        {
            get
            {
                if ((_Cidade == null))
                {
                    _Cidade = base.CreateObjectSet<Cidade>("Cidade");
                }
                return _Cidade;
            }
        }
        private ObjectSet<Cidade> _Cidade;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Endereco> Endereco
        {
            get
            {
                if ((_Endereco == null))
                {
                    _Endereco = base.CreateObjectSet<Endereco>("Endereco");
                }
                return _Endereco;
            }
        }
        private ObjectSet<Endereco> _Endereco;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Estado> Estado
        {
            get
            {
                if ((_Estado == null))
                {
                    _Estado = base.CreateObjectSet<Estado>("Estado");
                }
                return _Estado;
            }
        }
        private ObjectSet<Estado> _Estado;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Marca> Marca
        {
            get
            {
                if ((_Marca == null))
                {
                    _Marca = base.CreateObjectSet<Marca>("Marca");
                }
                return _Marca;
            }
        }
        private ObjectSet<Marca> _Marca;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Modelo> Modelo
        {
            get
            {
                if ((_Modelo == null))
                {
                    _Modelo = base.CreateObjectSet<Modelo>("Modelo");
                }
                return _Modelo;
            }
        }
        private ObjectSet<Modelo> _Modelo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produto
        {
            get
            {
                if ((_Produto == null))
                {
                    _Produto = base.CreateObjectSet<Produto>("Produto");
                }
                return _Produto;
            }
        }
        private ObjectSet<Produto> _Produto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Perfil> Perfil
        {
            get
            {
                if ((_Perfil == null))
                {
                    _Perfil = base.CreateObjectSet<Perfil>("Perfil");
                }
                return _Perfil;
            }
        }
        private ObjectSet<Perfil> _Perfil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PerfilUsuario> PerfilUsuario
        {
            get
            {
                if ((_PerfilUsuario == null))
                {
                    _PerfilUsuario = base.CreateObjectSet<PerfilUsuario>("PerfilUsuario");
                }
                return _PerfilUsuario;
            }
        }
        private ObjectSet<PerfilUsuario> _PerfilUsuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoEndereco> TipoEndereco
        {
            get
            {
                if ((_TipoEndereco == null))
                {
                    _TipoEndereco = base.CreateObjectSet<TipoEndereco>("TipoEndereco");
                }
                return _TipoEndereco;
            }
        }
        private ObjectSet<TipoEndereco> _TipoEndereco;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cidade EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCidade(Cidade cidade)
        {
            base.AddObject("Cidade", cidade);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Endereco EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEndereco(Endereco endereco)
        {
            base.AddObject("Endereco", endereco);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Estado EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstado(Estado estado)
        {
            base.AddObject("Estado", estado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Marca EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarca(Marca marca)
        {
            base.AddObject("Marca", marca);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modelo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModelo(Modelo modelo)
        {
            base.AddObject("Modelo", modelo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduto(Produto produto)
        {
            base.AddObject("Produto", produto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Perfil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPerfil(Perfil perfil)
        {
            base.AddObject("Perfil", perfil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PerfilUsuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPerfilUsuario(PerfilUsuario perfilUsuario)
        {
            base.AddObject("PerfilUsuario", perfilUsuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoEndereco EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoEndereco(TipoEndereco tipoEndereco)
        {
            base.AddObject("TipoEndereco", tipoEndereco);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Cidade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cidade : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cidade object.
        /// </summary>
        /// <param name="idCidade">Initial value of the IdCidade property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="uF">Initial value of the UF property.</param>
        public static Cidade CreateCidade(global::System.Int32 idCidade, global::System.String descricao, global::System.String uF)
        {
            Cidade cidade = new Cidade();
            cidade.IdCidade = idCidade;
            cidade.Descricao = descricao;
            cidade.UF = uF;
            return cidade;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCidade
        {
            get
            {
                return _IdCidade;
            }
            set
            {
                if (_IdCidade != value)
                {
                    OnIdCidadeChanging(value);
                    ReportPropertyChanging("IdCidade");
                    _IdCidade = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCidade");
                    OnIdCidadeChanged();
                }
            }
        }
        private global::System.Int32 _IdCidade;
        partial void OnIdCidadeChanging(global::System.Int32 value);
        partial void OnIdCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                OnUFChanging(value);
                ReportPropertyChanging("UF");
                _UF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UF");
                OnUFChanged();
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Cidade_Estado", "Estado")]
        public Estado Estado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("MVCTesteModel.FK_Cidade_Estado", "Estado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("MVCTesteModel.FK_Cidade_Estado", "Estado").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estado> EstadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("MVCTesteModel.FK_Cidade_Estado", "Estado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estado>("MVCTesteModel.FK_Cidade_Estado", "Estado", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Endereco_Cidade", "Endereco")]
        public EntityCollection<Endereco> Endereco
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Endereco>("MVCTesteModel.FK_Endereco_Cidade", "Endereco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Endereco>("MVCTesteModel.FK_Endereco_Cidade", "Endereco", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="cPF">Initial value of the CPF property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        public static Cliente CreateCliente(global::System.Int32 idCliente, global::System.String nome, global::System.String email, global::System.String cPF, global::System.DateTime dataNascimento)
        {
            Cliente cliente = new Cliente();
            cliente.IdCliente = idCliente;
            cliente.Nome = nome;
            cliente.Email = email;
            cliente.CPF = cPF;
            cliente.DataNascimento = dataNascimento;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Endereco_Cliente", "Endereco")]
        public EntityCollection<Endereco> Endereco
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Endereco>("MVCTesteModel.FK_Endereco_Cliente", "Endereco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Endereco>("MVCTesteModel.FK_Endereco_Cliente", "Endereco", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Endereco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Endereco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Endereco object.
        /// </summary>
        /// <param name="idEndereco">Initial value of the IdEndereco property.</param>
        /// <param name="idCidade">Initial value of the IdCidade property.</param>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="logradouro">Initial value of the Logradouro property.</param>
        /// <param name="numero">Initial value of the Numero property.</param>
        /// <param name="bairro">Initial value of the Bairro property.</param>
        public static Endereco CreateEndereco(global::System.Int32 idEndereco, global::System.Int32 idCidade, global::System.Int32 idCliente, global::System.String logradouro, global::System.Int32 numero, global::System.String bairro)
        {
            Endereco endereco = new Endereco();
            endereco.IdEndereco = idEndereco;
            endereco.IdCidade = idCidade;
            endereco.IdCliente = idCliente;
            endereco.Logradouro = logradouro;
            endereco.Numero = numero;
            endereco.Bairro = bairro;
            return endereco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEndereco
        {
            get
            {
                return _IdEndereco;
            }
            set
            {
                if (_IdEndereco != value)
                {
                    OnIdEnderecoChanging(value);
                    ReportPropertyChanging("IdEndereco");
                    _IdEndereco = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEndereco");
                    OnIdEnderecoChanged();
                }
            }
        }
        private global::System.Int32 _IdEndereco;
        partial void OnIdEnderecoChanging(global::System.Int32 value);
        partial void OnIdEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCidade
        {
            get
            {
                return _IdCidade;
            }
            set
            {
                OnIdCidadeChanging(value);
                ReportPropertyChanging("IdCidade");
                _IdCidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCidade");
                OnIdCidadeChanged();
            }
        }
        private global::System.Int32 _IdCidade;
        partial void OnIdCidadeChanging(global::System.Int32 value);
        partial void OnIdCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                OnIdClienteChanging(value);
                ReportPropertyChanging("IdCliente");
                _IdCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCliente");
                OnIdClienteChanged();
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Logradouro
        {
            get
            {
                return _Logradouro;
            }
            set
            {
                OnLogradouroChanging(value);
                ReportPropertyChanging("Logradouro");
                _Logradouro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Logradouro");
                OnLogradouroChanged();
            }
        }
        private global::System.String _Logradouro;
        partial void OnLogradouroChanging(global::System.String value);
        partial void OnLogradouroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.Int32 _Numero;
        partial void OnNumeroChanging(global::System.Int32 value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Endereco_Cidade", "Cidade")]
        public Cidade Cidade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cidade>("MVCTesteModel.FK_Endereco_Cidade", "Cidade").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cidade>("MVCTesteModel.FK_Endereco_Cidade", "Cidade").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cidade> CidadeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cidade>("MVCTesteModel.FK_Endereco_Cidade", "Cidade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cidade>("MVCTesteModel.FK_Endereco_Cidade", "Cidade", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Endereco_Cliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("MVCTesteModel.FK_Endereco_Cliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("MVCTesteModel.FK_Endereco_Cliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("MVCTesteModel.FK_Endereco_Cliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("MVCTesteModel.FK_Endereco_Cliente", "Cliente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Estado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Estado object.
        /// </summary>
        /// <param name="uF">Initial value of the UF property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Estado CreateEstado(global::System.String uF, global::System.String descricao)
        {
            Estado estado = new Estado();
            estado.UF = uF;
            estado.Descricao = descricao;
            return estado;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                if (_UF != value)
                {
                    OnUFChanging(value);
                    ReportPropertyChanging("UF");
                    _UF = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UF");
                    OnUFChanged();
                }
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Cidade_Estado", "Cidade")]
        public EntityCollection<Cidade> Cidade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cidade>("MVCTesteModel.FK_Cidade_Estado", "Cidade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cidade>("MVCTesteModel.FK_Cidade_Estado", "Cidade", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Marca")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Marca : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Marca object.
        /// </summary>
        /// <param name="idMarca">Initial value of the IdMarca property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Marca CreateMarca(global::System.Int32 idMarca, global::System.String descricao)
        {
            Marca marca = new Marca();
            marca.IdMarca = idMarca;
            marca.Descricao = descricao;
            return marca;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMarca
        {
            get
            {
                return _IdMarca;
            }
            set
            {
                if (_IdMarca != value)
                {
                    OnIdMarcaChanging(value);
                    ReportPropertyChanging("IdMarca");
                    _IdMarca = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdMarca");
                    OnIdMarcaChanged();
                }
            }
        }
        private global::System.Int32 _IdMarca;
        partial void OnIdMarcaChanging(global::System.Int32 value);
        partial void OnIdMarcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Modelo_Marca", "Modelo")]
        public EntityCollection<Modelo> Modelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Modelo>("MVCTesteModel.FK_Modelo_Marca", "Modelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Modelo>("MVCTesteModel.FK_Modelo_Marca", "Modelo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Modelo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modelo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Modelo object.
        /// </summary>
        /// <param name="idModelo">Initial value of the IdModelo property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="idMarca">Initial value of the IdMarca property.</param>
        public static Modelo CreateModelo(global::System.Int32 idModelo, global::System.String descricao, global::System.Int32 idMarca)
        {
            Modelo modelo = new Modelo();
            modelo.IdModelo = idModelo;
            modelo.Descricao = descricao;
            modelo.IdMarca = idMarca;
            return modelo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdModelo
        {
            get
            {
                return _IdModelo;
            }
            set
            {
                if (_IdModelo != value)
                {
                    OnIdModeloChanging(value);
                    ReportPropertyChanging("IdModelo");
                    _IdModelo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdModelo");
                    OnIdModeloChanged();
                }
            }
        }
        private global::System.Int32 _IdModelo;
        partial void OnIdModeloChanging(global::System.Int32 value);
        partial void OnIdModeloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMarca
        {
            get
            {
                return _IdMarca;
            }
            set
            {
                OnIdMarcaChanging(value);
                ReportPropertyChanging("IdMarca");
                _IdMarca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdMarca");
                OnIdMarcaChanged();
            }
        }
        private global::System.Int32 _IdMarca;
        partial void OnIdMarcaChanging(global::System.Int32 value);
        partial void OnIdMarcaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Modelo_Marca", "Marca")]
        public Marca Marca
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("MVCTesteModel.FK_Modelo_Marca", "Marca").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("MVCTesteModel.FK_Modelo_Marca", "Marca").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Marca> MarcaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("MVCTesteModel.FK_Modelo_Marca", "Marca");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Marca>("MVCTesteModel.FK_Modelo_Marca", "Marca", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Produto_Modelo", "Produto")]
        public EntityCollection<Produto> Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produto>("MVCTesteModel.FK_Produto_Modelo", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produto>("MVCTesteModel.FK_Produto_Modelo", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Perfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Perfil object.
        /// </summary>
        /// <param name="idPerfil">Initial value of the IdPerfil property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Perfil CreatePerfil(global::System.Int32 idPerfil, global::System.String descricao)
        {
            Perfil perfil = new Perfil();
            perfil.IdPerfil = idPerfil;
            perfil.Descricao = descricao;
            return perfil;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPerfil
        {
            get
            {
                return _IdPerfil;
            }
            set
            {
                if (_IdPerfil != value)
                {
                    OnIdPerfilChanging(value);
                    ReportPropertyChanging("IdPerfil");
                    _IdPerfil = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPerfil");
                    OnIdPerfilChanged();
                }
            }
        }
        private global::System.Int32 _IdPerfil;
        partial void OnIdPerfilChanging(global::System.Int32 value);
        partial void OnIdPerfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_PerfilUsuario_Perfil", "PerfilUsuario")]
        public EntityCollection<PerfilUsuario> PerfilUsuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PerfilUsuario>("MVCTesteModel.FK_PerfilUsuario_Perfil", "PerfilUsuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PerfilUsuario>("MVCTesteModel.FK_PerfilUsuario_Perfil", "PerfilUsuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="PerfilUsuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PerfilUsuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PerfilUsuario object.
        /// </summary>
        /// <param name="idPerfil">Initial value of the IdPerfil property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="dataAutorizacao">Initial value of the DataAutorizacao property.</param>
        public static PerfilUsuario CreatePerfilUsuario(global::System.Int32 idPerfil, global::System.Int32 idUsuario, global::System.DateTime dataAutorizacao)
        {
            PerfilUsuario perfilUsuario = new PerfilUsuario();
            perfilUsuario.IdPerfil = idPerfil;
            perfilUsuario.IdUsuario = idUsuario;
            perfilUsuario.DataAutorizacao = dataAutorizacao;
            return perfilUsuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPerfil
        {
            get
            {
                return _IdPerfil;
            }
            set
            {
                if (_IdPerfil != value)
                {
                    OnIdPerfilChanging(value);
                    ReportPropertyChanging("IdPerfil");
                    _IdPerfil = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPerfil");
                    OnIdPerfilChanged();
                }
            }
        }
        private global::System.Int32 _IdPerfil;
        partial void OnIdPerfilChanging(global::System.Int32 value);
        partial void OnIdPerfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataAutorizacao
        {
            get
            {
                return _DataAutorizacao;
            }
            set
            {
                OnDataAutorizacaoChanging(value);
                ReportPropertyChanging("DataAutorizacao");
                _DataAutorizacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataAutorizacao");
                OnDataAutorizacaoChanged();
            }
        }
        private global::System.DateTime _DataAutorizacao;
        partial void OnDataAutorizacaoChanging(global::System.DateTime value);
        partial void OnDataAutorizacaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_PerfilUsuario_Perfil", "Perfil")]
        public Perfil Perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Perfil>("MVCTesteModel.FK_PerfilUsuario_Perfil", "Perfil").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Perfil>("MVCTesteModel.FK_PerfilUsuario_Perfil", "Perfil").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Perfil> PerfilReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Perfil>("MVCTesteModel.FK_PerfilUsuario_Perfil", "Perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Perfil>("MVCTesteModel.FK_PerfilUsuario_Perfil", "Perfil", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_PerfilUsuario_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("MVCTesteModel.FK_PerfilUsuario_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("MVCTesteModel.FK_PerfilUsuario_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("MVCTesteModel.FK_PerfilUsuario_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("MVCTesteModel.FK_PerfilUsuario_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="idProduto">Initial value of the IdProduto property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="preco">Initial value of the Preco property.</param>
        /// <param name="idModelo">Initial value of the IdModelo property.</param>
        public static Produto CreateProduto(global::System.Int32 idProduto, global::System.String descricao, global::System.Decimal preco, global::System.Int32 idModelo)
        {
            Produto produto = new Produto();
            produto.IdProduto = idProduto;
            produto.Descricao = descricao;
            produto.Preco = preco;
            produto.IdModelo = idModelo;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProduto
        {
            get
            {
                return _IdProduto;
            }
            set
            {
                if (_IdProduto != value)
                {
                    OnIdProdutoChanging(value);
                    ReportPropertyChanging("IdProduto");
                    _IdProduto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProduto");
                    OnIdProdutoChanged();
                }
            }
        }
        private global::System.Int32 _IdProduto;
        partial void OnIdProdutoChanging(global::System.Int32 value);
        partial void OnIdProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdModelo
        {
            get
            {
                return _IdModelo;
            }
            set
            {
                OnIdModeloChanging(value);
                ReportPropertyChanging("IdModelo");
                _IdModelo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdModelo");
                OnIdModeloChanged();
            }
        }
        private global::System.Int32 _IdModelo;
        partial void OnIdModeloChanging(global::System.Int32 value);
        partial void OnIdModeloChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_Produto_Modelo", "Modelo")]
        public Modelo Modelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("MVCTesteModel.FK_Produto_Modelo", "Modelo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("MVCTesteModel.FK_Produto_Modelo", "Modelo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Modelo> ModeloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("MVCTesteModel.FK_Produto_Modelo", "Modelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Modelo>("MVCTesteModel.FK_Produto_Modelo", "Modelo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="TipoEndereco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoEndereco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoEndereco object.
        /// </summary>
        /// <param name="idTipoEndereco">Initial value of the IdTipoEndereco property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static TipoEndereco CreateTipoEndereco(global::System.Int32 idTipoEndereco, global::System.String descricao)
        {
            TipoEndereco tipoEndereco = new TipoEndereco();
            tipoEndereco.IdTipoEndereco = idTipoEndereco;
            tipoEndereco.Descricao = descricao;
            return tipoEndereco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoEndereco
        {
            get
            {
                return _IdTipoEndereco;
            }
            set
            {
                if (_IdTipoEndereco != value)
                {
                    OnIdTipoEnderecoChanging(value);
                    ReportPropertyChanging("IdTipoEndereco");
                    _IdTipoEndereco = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTipoEndereco");
                    OnIdTipoEnderecoChanged();
                }
            }
        }
        private global::System.Int32 _IdTipoEndereco;
        partial void OnIdTipoEnderecoChanging(global::System.Int32 value);
        partial void OnIdTipoEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCTesteModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        public static Usuario CreateUsuario(global::System.Int32 idUsuario, global::System.String login, global::System.String senha)
        {
            Usuario usuario = new Usuario();
            usuario.IdUsuario = idUsuario;
            usuario.Login = login;
            usuario.Senha = senha;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCTesteModel", "FK_PerfilUsuario_Usuario", "PerfilUsuario")]
        public EntityCollection<PerfilUsuario> PerfilUsuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PerfilUsuario>("MVCTesteModel.FK_PerfilUsuario_Usuario", "PerfilUsuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PerfilUsuario>("MVCTesteModel.FK_PerfilUsuario_Usuario", "PerfilUsuario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
